[colors-dark]
# Base16 Black Metal - foot color config
# Scheme by metalelf0 (https://github.com/metalelf0)

background=000000
foreground=c1c1c1

# normal
regular0=000000
regular1=5f8787
regular2=dd9999
regular3=a06666
regular4=888888
regular5=999999
regular6=aaaaaa
regular7=c1c1c1

# bright
bright0=333333
bright1=aaaaaa
bright2=121212
bright3=222222
bright4=999999
bright5=999999
bright6=444444
bright7=c1c1c1

# misc
selection-background=c1c1c1
selection-foreground=000000
urls=999999
jump-labels=000000 a06666
scrollback-indicator=000000 999999

[main]
font=Fira Code:size=16
#[csd]
#preferred=none
