[colors-dark]
alpha=0.8
# Base16 Bright - foot color config
# Scheme by Chris Kempson (http://chriskempson.com)

background=000000
foreground=e0e0e0

# normal
regular0=000000
regular1=fb0120
regular2=a1c659
regular3=fda331
regular4=6fb3d2
regular5=d381c3
regular6=76c7b7
regular7=e0e0e0

# bright
bright0=b0b0b0
bright1=fc6d24
bright2=303030
bright3=505050
bright4=d0d0d0
bright5=f5f5f5
bright6=be643c
bright7=ffffff

# extended
16=fc6d24
17=be643c
18=303030
19=505050
20=d0d0d0
21=f5f5f5

# misc
selection-background=e0e0e0
selection-foreground=000000
urls=d0d0d0
jump-labels=000000 fda331
scrollback-indicator=000000 d0d0d0

[main]
font=Fira Code:size=16
#[csd]
#preferred=none
