[icons]
icons = "awesome6"

[theme]
theme = "native"

[[block]]
block = "custom"
command = "echo \uf0c9"
interval = "once"

[[block.click]]
button = "left"
cmd = "wofi -S drun"

[[block]]
block = "custom"
command	= "echo	\uf08b"
interval = "once"

[[block.click]]
button = "left"
cmd = "wlogout"

[[block]]
block = "custom"
command = "echo \uf030"
interval = "once"

[[block.click]]
button = "left"
cmd = "slurp | grim -g - - | wl-copy"

[[block]]
block = "custom"
command = "echo \uf07b"
interval = "once"

[[block.click]]
button = "left"
cmd = "thunar"

[[block]]
block = "custom"
command = "echo	\uf120"
interval = "once"

[[block.click]]
button = "left"
cmd = "foot"

[[block]]
block = "custom"
command = "echo \uf132"
interval = "once"

[[block.click]]
button = "left"
cmd = "flatpak run com.bitwarden.desktop"

[[block]]
block = "custom"
command = "echo \uf2c6"
interval = "once"

[[block.click]]
button = "left"
cmd = "flatpak run org.telegram.desktop"

[[block]]
block = "custom"
command = "echo \uf392"
interval = "once"

[[block.click]]
button = "left"
cmd = "flatpak run dev.vencord.Vesktop"

[[block]]
block = "custom"
command = "echo	\uf044"
interval = "once"

[[block.click]]
button = "left"
cmd = "flatpak run com.github.flxzt.rnote"

[[block]]
block = "custom"
command = "echo	\ue007"
interval = "once"

[[block.click]]
button = "left"
cmd = "firefox"

[[block]]
block = "custom"
format = " \uf11c "
cycle = ["pkill wvkbd-deskintl --signal SIGUSR1", "pkill wvkbd-deskintl --signal SIGUSR2"]
interval = "once"

[[block.click]]
button = "left"
action = "cycle"

[[block]]
block = "custom"
command = "echo 1"
interval = "once"

[[block.click]]
button = "left"
cmd = "swaymsg move workspace 1"

[[block]]
block = "custom"
command = "echo 2"
interval = "once"

[[block.click]]
button = "left"
cmd = "swaymsg move workspace 2"

[[block]]
block = "custom"
command = "echo 3"
interval = "once"

[[block.click]]
button = "left"
cmd = "swaymsg move workspace 3"

[[block]]
block = "custom"
command = "echo \uf0a8"
interval = "once"

[[block.click]]
button = "left"
cmd = "swaymsg focus prev"

[[block]]
block = "custom"
command = "echo \uf0a9"
interval = "once"

[[block.click]]
button = "left"
cmd = "swaymsg focus next"

[[block]]
block = "custom"
command = "echo \uf063"
interval = "once"

[[block.click]]
button = "left"
cmd = "swaymsg resize grow height 10px"

[[block]]
block = "custom"
command = "echo \uf062"
interval = "once"

[[block.click]]
button = "left"
cmd = "swaymsg resize shrink height 10px"

[[block]]
block = "custom"
format = " \uf065 "
cycle = ["swaymsg gaps inner current set 0", "swaymsg gaps inner current set 10"]
interval = "once"

[[block.click]]
button = "left"
action = "cycle"

[[block]]
block = "custom"
command = "echo \uf2d2"
interval = "once"

[[block.click]]
button = "left"
cmd = "swaymsg floating toggle"

[[block.click]]
button = "left"
cmd = "swaymsg kill"

[[block]]
block = "custom"
command = "echo \uf00d"
interval = "once"

[[block.click]]
button = "left"
cmd = "swaymsg kill"
